const AUTHENTICATED_SUCCESSULLY = 'AUTHENTICATED_SUCCESSULLY';
const LOGOUT = 'LOGOUT';
const LOGUP = 'LOGUP';
const AUTHENTICATED_UNSUCCESSULLY = 'AUTHENTICATED_UNSUCCESSULLY';
const SESSION = 'SESSION';
const ADD_SESSION = 'ADD_SESSION';
const DELETE_SESSION = 'DELETE_SESSION';
const USER_CHAT = 'USER_CHAT';
const GET_VEGETABLES_DB = 'GET_VEGETABLES_DB';
const GET_MOONCALENDAR_DB = 'GET_MOONCALENDAR_DB';
const GET_ARTICLE_DB = 'GET_ARTICLE_DB';
const MODAL_LOGIN = 'MODAL_LOGIN';
const PAGE_THEME = 'PAGE_THEME';
const UPDATE_COMMENTS_ARRAY = 'UPDATE_COMMENTS_ARRAY';
const CREATE_GARDEN = 'CREATE_GARDEN';
const PAGE_DEFAULT = 'PAGE_DEFAULT';
const SUPPORT = 'SUPPORT';

export {
  AUTHENTICATED_SUCCESSULLY, LOGOUT, LOGUP, AUTHENTICATED_UNSUCCESSULLY,
  SESSION, ADD_SESSION, DELETE_SESSION, USER_CHAT, GET_VEGETABLES_DB,
  GET_MOONCALENDAR_DB, GET_ARTICLE_DB, MODAL_LOGIN, PAGE_THEME,
  UPDATE_COMMENTS_ARRAY, CREATE_GARDEN, PAGE_DEFAULT, SUPPORT,
};
