const AUTHENTICATED_SUCCESSULLY = 'AUTHENTICATED_SUCCESSULLY';
const LOGOUT = 'LOGOUT';
const LOGUP = 'LOGUP';
const AUTHENTICATED_UNSUCCESSULLY = 'AUTHENTICATED_UNSUCCESSULLY';
const SESSION = 'SESSION';
const ADD_SESSION = 'ADD_SESSION';
const DELETE_SESSION = 'DELETE_SESSION';

export {
  AUTHENTICATED_SUCCESSULLY, LOGOUT, LOGUP, AUTHENTICATED_UNSUCCESSULLY,
  SESSION, ADD_SESSION, DELETE_SESSION,
};

export const GET_VEGETABLES_DB = 'GET_VEGETABLES_DB';
export const GET_MOONCALENDAR_DB = 'GET_MOONCALENDAR_DB';
export const MODAL_LOGIN = 'MODAL_LOGIN';
