const AUTHENTICATED_SUCCESSULLY = 'AUTHENTICATED_SUCCESSULLY';
const LOGOUT = 'LOGOUT';
const LOGUP = 'LOGUP';
const AUTHENTICATED_UNSUCCESSULLY = 'AUTHENTICATED_UNSUCCESSULLY';
const SESSION = 'SESSION';
const ADD_SESSION = 'ADD_SESSION';
const DELETE_SESSION = 'DELETE_SESSION';

export {
  AUTHENTICATED_SUCCESSULLY, LOGOUT, LOGUP, AUTHENTICATED_UNSUCCESSULLY,
  SESSION, ADD_SESSION, DELETE_SESSION,
};

export const GET_VEGETABLES_DB = 'GET_VEGETABLES_DB';
export const GET_MOONCALENDAR_DB = 'GET_MOONCALENDAR_DB';
export const GET_ARTICLE_DB = 'GET_ARTICLE_DB';
export const MODAL_LOGIN = 'MODAL_LOGIN'
export const PAGE_THEME = 'PAGE_THEME'
export const UPDATE_COMMENTS_ARRAY = 'UPDATE_COMMENTS_ARRAY';
export const CREATE_GARDEN = 'CREATE_GARDEN';
export const PAGE_DEFAULT = 'PAGE_DEFAULT'

